export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#4c4162',
        'on-primary-container': '#9783bd',
        'secondary-container': '#af8d11',
        outline: '#948e99',
        'surface-container-highest': '#353531',
        'secondary-fixed-dim': '#e9c349',
        error: '#ffb4ab',
        'on-secondary-container': '#342800',
        'on-primary-fixed-variant': '#4f3d72',
        'on-error': '#690005',
        'on-background': '#e5e2dc',
        'inverse-primary': '#68558b',
        'on-secondary': '#3c2f00',
        'on-surface-variant': '#cbc4d0',
        surface: '#131410',
        primary: '#d2bcfa',
        'surface-tint': '#d2bcfa',
        'on-secondary-fixed-variant': '#574500',
        background: '#131410',
        'tertiary-container': '#2a203e',
        'on-tertiary': '#352b4a',
        'primary-container': '#2d1b4e',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#cec0e7',
        'primary-fixed': '#ebddff',
        'outline-variant': '#49454e',
        'surface-variant': '#353531',
        'on-error-container': '#ffdad6',
        'surface-container': '#20201c',
        'on-tertiary-fixed': '#201634',
        'surface-container-lowest': '#0e0e0b',
        'on-surface': '#e5e2dc',
        'on-tertiary-container': '#9387ab',
        secondary: '#e9c349',
        tertiary: '#cec0e7',
        'on-primary-fixed': '#231043',
        'surface-bright': '#3a3935',
        'surface-container-high': '#2a2a26',
        'tertiary-fixed': '#eaddff',
        'inverse-surface': '#e5e2dc',
        'inverse-on-surface': '#31312d',
        'on-primary': '#38265a',
        'on-secondary-fixed': '#241a00',
        'secondary-fixed': '#ffe088',
        'surface-dim': '#131410',
        'surface-container-low': '#1c1c18',
        'primary-fixed-dim': '#d2bcfa',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        unit: '8px',
        'container-max': '1200px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['Literata', 'serif'],
        'headline-md': ['Literata', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg-mobile': ['Literata', 'serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg': ['Literata', 'serif'],
        caption: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
